import { IconProps } from '@phosphor-icons/react'
import { ReactNode } from 'react'

import { ESizes } from '@types'

export type TIconSize = IconProps['size'] | IconSizes

export type TIconProps = Omit<IconProps, 'color' | 'size'> & {
  icon: TIcon
  color?: IconProps['color']
  size?: TIconSize
}

export type TContextValue = TIconProps & {
  componentName?: string
}

export type TProviderProps = {
  children: ReactNode
  value: TIconProps
}

export type IconSizes = ESizes.XS | ESizes.SM | ESizes.MD | ESizes.LG | ESizes.XL

export type TIcon =
  | 'bookmark'
  | 'magnifying-glass'
  | 'caret-up'
  | 'caret-down'
  | 'caret-left'
  | 'caret-right'
  | 'x'
  | 'x-circle'
  | 'house'
  | 'check'
  | 'user'
  | 'user-circle'
  | 'books'
  | 'book'
  | 'book-bookmark'
  | 'book-open'
  | 'book-open-text'
  | 'book-open-user'
  | 'bookmark-simple'
  | 'bookmarks'
  | 'bookmarks-simple'
  | 'asterisk'
  | 'at'
  | 'backspace'
  | 'bell'
  | 'bell-ringing'
  | 'bell-slash'
  | 'calendar'
  | 'cards'
  | 'circle'
  | 'circle-dashed'
  | 'clipboard'
  | 'control'
  | 'copy'
  | 'copy-simple'
  | 'copyright'
  | 'desktop'
  | 'device-mobile'
  | 'devices'
  | 'dot'
  | 'dot-outline'
  | 'dots-three'
  | 'dots-three-vertical'
  | 'dots-three-outline'
  | 'dots-three-outline-vertical'
  | 'download'
  | 'download-simple'
  | 'exclamation-mark'
  | 'export'
  | 'eye'
  | 'eye-closed'
  | 'eye-slash'
  | 'faders'
  | 'faders-horizontal'
  | 'file'
  | 'files'
  | 'flag'
  | 'flask'
  | 'folder'
  | 'folder-simple'
  | 'folder-plus'
  | 'folder-minus'
  | 'folder-lock'
  | 'folder-dashed'
  | 'folders'
  | 'flying-saucer'
  | 'flower-tulip'
  | 'flower-lotus'
  | 'flame'
  | 'fish'
  | 'finn-the-human'
  | 'feather'
  | 'eyes'
  | 'dog'
  | 'detective'
  | 'crown'
  | 'cowboy-hat'
  | 'dev-to-logo'
  | 'cow'
  | 'compass-rose'
  | 'coffee'
  | 'code'
  | 'clover'
  | 'chef-hat'
  | 'church'
  | 'cheese'
  | 'chart-line'
  | 'carrot'
  | 'cat'
  | 'car-profile'
  | 'campfire'
  | 'cake'
  | 'cactus'
  | 'butterfly'
  | 'bug'
  | 'brain'
  | 'boxing-glove'
  | 'bomb'
  | 'biohazard'
  | 'bird'
  | 'bathtub'
  | 'axe'
  | 'baby'
  | 'anchor'
  | 'alien'
  | 'funnel'
  | 'funnel-x'
  | 'game-controller'
  | 'gear'
  | 'ghost'
  | 'google-logo'
  | 'guitar'
  | 'hash'
  | 'heart'
  | 'horse'
  | 'image'
  | 'info'
  | 'key'
  | 'lego-smiley'
  | 'link'
  | 'link-simple'
  | 'lock'
  | 'lock-open'
  | 'map-pin'
  | 'minus'
  | 'minus-circle'
  | 'moon'
  | 'moon-stars'
  | 'number-one'
  | 'number-two'
  | 'number-three'
  | 'number-four'
  | 'number-five'
  | 'number-six'
  | 'number-seven'
  | 'number-eight'
  | 'number-nine'
  | 'number-zero'
  | 'paperclip'
  | 'pencil'
  | 'pencil-simple'
  | 'plus'
  | 'plus-circle'
  | 'push-pin'
  | 'push-pin-slash'
  | 'question'
  | 'question-mark'
  | 'rabbit'
  | 'robot'
  | 'share'
  | 'shrimp'
  | 'skull'
  | 'sliders'
  | 'sliders-horizontal'
  | 'spinner'
  | 'stack'
  | 'star'
  | 'sun'
  | 'trash'
  | 'wrench'
