name: Generate Changelog

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate changelog
        run: npx conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes (if any)
        run: |
          git add CHANGELOG.md
          if git diff --cached --quiet; then
            echo "No changes to commit"; echo "HAS_CHANGES=false" >> $GITHUB_ENV
          else
            git commit -m "docs: update changelog"
            echo "HAS_CHANGES=true" >> $GITHUB_ENV
          fi

      - name: Create / Update PR
        if: env.HAS_CHANGES == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/changelog
          base: master
          title: "docs: update changelog"
          commit-message: "docs: update changelog"
          body: |
            This PR updates the CHANGELOG.md based on conventional commits.
          labels: documentation, automated-pr
          signoff: false
          delete-branch: true
